name: "Chess"

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'chess|')
    steps:
    - if: startsWith(github.event.issue.title, 'chess|') && contains(github.event.issue.labels.*.name, 'test')
      run: |
        # the triggering issue contains test
        echo "${{ github.event_name }}"
        exit 1

    - name: Set env vars
      run: |
        echo "${{ github.event_name }}"
        echo "REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
        echo "EVENT_ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
        echo "EVENT_USER_LOGIN=${{ github.event.issue.user.login }}" >> $GITHUB_ENV

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Setup Gems
      run: |
        gem install activesupport -v 7.0.3 -N --silent
        gem install octokit -v 5.1.0 -N --silent
        gem install chess -v 0.3.3 -N --silent

    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}

    - name: Check Path
      run: echo $PWD
      shell: bash

    - name: Play
      run: ruby scripts/play.rb
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push changes to README.md
      run: |
        git config --global user.name 'Ghost'
        git config --global user.email 'ghost@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add README.md
        git commit -m "updated chess board"
        git push


